### ISSUE TITLE
Login as other user and then elevate as root

### ISSUE THREAD

**Issue by andremain** [AlexxIT/SSHCommand#26]
I am trying to login to my synology using my user and then elevate to root and then run a command using a home assistant script.

This is what i have so far:

```
service: ssh_command.exec_command
data:
  host: 10.10.10.245
  port: 22
  user: andremain
  pass: password
  command: ssh -p password root@10.10.10.254 -i sudo synonet --wake "54:04:a6:28:d4:fa" eth0
```

Please help!
