### ISSUE TITLE
SSH_Command in Configuration.yaml

### ISSUE THREAD

**Issue by labouman** [AlexxIT/SSHCommand#28]
I have a question about SSH_Command i've added it in configuration.yaml als you discribed with the link to secret and then i can't find out how to select is when i want to send a command to that specific host.

**Comment by AlexxIT** [comment]
I don't understand question.

**Comment by labouman** [comment]
i've added the following to my configuration.yaml 
```
ssh_command:
  host: 192.168.1.123
  port: 22
  user: pi
  pass: !secret ssh_parssword
```
And now i want to use this configuration inside an automation to exacute an SSH_command to this specific host without filling it all up again.
