### ISSUE TITLE
Tip: How to use ssh keys

### ISSUE THREAD

**Issue by jonskoglund** [AlexxIT/SSHCommand#34]
Hi. I tested the folllowing script and it works:
```
run_on_host:
  alias: Run shell command on host
  sequence:
  - action: ssh_command.exec_command
    data:
      host: 192.168.1.130
      user: someusername
      pass: secretpassword
      command: osascript -e 'display notification "The command finished" with title
        "Success"'
```
But my goal is to make this code more secure by using ssh keys. The documentation is using this code:
```
script:
  run_on_host:
    alias: Run shell command on host
    sequence:
    - service: ssh_command.exec_command
      data:
        host: 192.168.1.123
        user: pi
        private_key: /config/ssh/id_rsa
        command: ls -la
```
I know how to make ssh keys and how to copy the public ssh key from homeassistant to my other pc. However I get confused by the ssh folders on my homeassistant and your instructions. /config/ssh/ directory doesn't exist on my setup. And what to do with the ssh key? This key is created in /root/.ssh when I run ssh-keygen command.
Via terminal in Homeassistant I can find two ssh folders:
```
/root/.ssh (same as /data/.ssh)
/config/.ssh
```
After some googling I found that both the private and public key needs to be copied from /root/.ssh to /config/ssh/. Using these instructions:
```
cd /root/config
mkdir ssh
cp /root/.ssh/id_rsa.pub /root/config/ssh/id_rsa.pub
cp /root/.ssh/id_rsa /root/config/ssh/id_rsa
```
Maybe add these instructions to the readme?
