### ISSUE TITLE
Unable to SSH hate to Pi

### ISSUE THREAD

**Issue by oneseventhree** [AlexxIT/SSHCommand#36]
Hi,

I am unsure why I can't get this to work:
```
sequence:
  - action: ssh_command.exec_command
    metadata: {}
    data:
      command: sudo reboot
      host: 192.168.1.189
      port: 8090
      user: xxx
      pass: xxx
alias: HyperHDR - Shutdown
```
I've also tried:
command: reboot
with no success.

It works when I do it through terminal(mac):
<img width="652" alt="Image" src="https://github.com/user-attachments/assets/da6b8200-515c-4d87-b6c6-14937242b6d9" />

What am I doing wrong?

Also, I've added this into config.yaml:
```
# SSH - HyperHDR
ssh_command:
  host: 192.168.1.189
  port: 8090
  user: !secret hyperhdr_username
  pass: !secret hyperhdr_password
```

How do I use this in the script?

Thanks in advance!
